# Alpine Linux是一个轻型Linux发行版，它不同于通常的Linux发行版，https://www.alpinelinux.org
# Alpine采用了musl libc 和 BusyBox以减少系统的体积和运行时的资源消耗。Alpine Linux提供了自己的包管理工具：apk
# 可以通过https://pkgs.alpinelinux.org/packages 查询包信息
# 据说Docker官方也已开始推荐使用Alpine替代之前的Ubuntu来作为基础镜像，好处包括镜像下载速度加快，镜像安全性提高，占用更少的主机磁盘空间等。
#FROM openjdk:8-jdk-alpine
#RUN apk add --no-cache curl tar bash procps

FROM ml_jenkins

ARG MAVEN_VERSION=3.6.1
ARG USER_HOME_DIR="/root"
ARG SHA=b4880fb7a3d81edd190a029440cdf17f308621af68475a4fe976296e71ff4a4b546dd6d8a58aaafba334d309cc11e638c52808a4b0e818fc0fd544226d952544
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

#COPY mvn-entrypoint.sh /usr/local/bin/mvn-entrypoint.sh
COPY settings-docker.xml /usr/share/maven/ref/

#ENTRYPOINT ["/usr/local/bin/mvn-entrypoint.sh"]

# 注意：无-i参数bash命令时没有反馈(docker build -t ml_mvn -f Dockerfile-maven .)
# docker build -t ml_mvn -f Dockerfile-maven .